#!/bin/bash

NCCL_P2P_DISABLE=1 NCCL_IB_DISABLE=1 deepspeed --num_gpus 2 src/train_bash.py \
    --deepspeed /root/LLaMA-Factory-PradaLAB/scripts/ds_z2_config.json \
    --stage sft \
    --do_train \
    --model_name_or_path /root/autodl-tmp/models/llama-8b-instruct-pro \
    --dataset math_10k \
    --template default \
    --finetuning_type freeze \
    --name_module_trainable all \
    --num_layer_trainable 2 \
    --use_llama_pro \
    --output_dir /root/autodl-tmp/train_exps/llamapro_llama-8b-instruct-pro_math10k_lr9e-4_pbs2_ga16 \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 1024 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --warmup_steps 20 \
    --save_steps 100 \
    --eval_steps 100 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --learning_rate 9e-4 \
    --num_train_epochs 2.0 \
    --max_samples 3000 \
    --val_size 0.1 \
    --plot_loss \
    --fp16
